#!/bin/bash

[[ ${BASH_DEBUG:-false} = true ]] && set -x

# Constants
MODULE="$(basename "$0")"

# Color Palette
COLOR_RESET='\033[0m'
COLOR_BOLD='\033[1m'

## Foreground	(FG)
FG_BLACK='\033[38;5;0m'
FG_RED='\033[38;5;1m'
FG_GREEN='\033[38;5;2m'
FG_YELLOW='\033[38;5;3m'
FG_BLUE='\033[38;5;4m'
FG_MAGENTA='\033[38;5;5m'
FG_CYAN='\033[38;5;6m'
FG_WHITE='\033[38;5;7m'

## Background	(BG)
BG_BLACK='\033[48;5;0m'
BG_RED='\033[48;5;1m'
BG_GREEN='\033[48;5;2m'
BG_YELLOW='\033[48;5;3m'
BG_BLUE='\033[48;5;4m'
BG_MAGENTA='\033[48;5;5m'
BG_CYAN='\033[48;5;6m'
BG_WHITE='\033[48;5;7m'

# Functions

########################
# Print to STDERR
# Arguments:
#   Message to print
# Returns:
#   None
#########################
stderr_print() {
    printf "%b\\n" "${*}" >&2
}

########################
# Log message
# Arguments:
#   Message to log
# Returns:
#   None
#########################
log() {
    #stderr_print "${date -Iseconds}${NAMI_DEBUG:+${CYAN}${MODULE:-} ${MAGENTA}$(date "+%T.%2N ")}${RESET}${*}"
	stderr_print "$(date +'%FT%T.%3N') : ${NAMI_DEBUG:+${FG_CYAN}${MODULE:-} ${FG_MAGENTA}$(date "+%T.%2N ")}${COLOR_RESET}${*}"
}
########################
# Log an 'info' message
# Arguments:
#   Message to log
# Returns:
#   None
#########################
info() {
    log "${FG_GREEN}INFO ${COLOR_RESET} ==> ${*}"
}
########################
# Log message
# Arguments:
#   Message to log
# Returns:
#   None
#########################
warn() {
    log "${FG_YELLOW}WARN ${COLOR_RESET} ==> ${*}"
}
########################
# Log an 'error' message
# Arguments:
#   Message to log
# Returns:
#   None
#########################
error() {
    log "${FG_RED}ERROR${COLOR_RESET} ==> ${*}"
}

########################
# Log an 'trace' message
# Arguments:
#   Message to log
# Returns:
#   None
#########################
trace() {
    log "${FG_BLUE}TRACE${COLOR_RESET} ==> ${*}"
}
